### ISSUE TITLE
Unable to handle parallel runs?

### ISSUE THREAD

**Issue by SSKLCP** [jakubfijalkowski/kvenv#2]
Hey there, 

Thanks for making this tool, I've been trying to put it to use with Atlantis and it seems to fit a niche I was looking for! 

However one thing that I've noticed is that when using parallel runs on Atlantis one of the runs seem to fail. 

If I ask it to plan in parallel (I've tried max 2 in parallel) then one of the plans will always fail, not consistent which one. But if I remove parallel runs then it does it without issue. So I feel like it's something about it not being able to run two instances / there being a shared dependency that can't handle two accesses at once. 

Maybe not an issue with kvenv but more my understanding but though it good to discuss :) 

Here's the error I get: 

```
running "kvenv run-in --azure -n \"$HEAD_REPO_NAME\" --azure-keyvault-name \"$KVENV_KEYVAULT_NAME\" --mask KVENV_CLIENT_SECRET -- terragrunt init -no-color" in "/root/.atlantis/repos/xxx/Atlantis-Test/Atlantis-Test/6/environments_prod_static-site/environments/prod/static-site": exit status 1: running "kvenv run-in --azure -n \"$HEAD_REPO_NAME\" --azure-keyvault-name \"$KVENV_KEYVAULT_NAME\" --mask KVENV_CLIENT_SECRET -- terragrunt init -no-color" in "/root/.atlantis/repos/xxx/Atlantis-Test/Atlantis-Test/6/environments_prod_static-site/environments/prod/static-site": 
Error: cannot load environment

Caused by:
    0: Azure configuration error
    1: non-io error occurred which will not be retried
    2: failed to get bearer token
    3: Multiple errors were encountered while attempting to authenticate:
       getting managed identity credential timed out
       error getting token credential from Azure CLI
```

**Comment by jakubfijalkowski** [comment]
Hey! Thanks for the report! Happy that the tool is useful :)

This is related to the [Azure SDK for Rust](https://github.com/azure/azure-sdk-for-rust) that `kvenv` uses underneath - it cannot get the token. I see that you use `KVENV_`-prefixed variables for the configuration - these are not used by `kvenv` directly anymore. These were used only in v0.1.0. In v0.2.0 I switched to a more standard `AZURE_`-prefixed variables that all the other Azure tooling uses. Renaming the variables to `AZURE_TENANT_ID`, `AZURE_CLIENT_ID` and `AZURE_CLIENT_SECRET` should force kvenv to use service account-based auth.

I suspect it fails randomly because of  a default credential mechanisms - if the env variables are not specified, then `kvenv` falls back to it. It means, that the Azure SDK will first try to get the credentials from env (which it cannot find), then it will try to get Managed Service Identity credentials, then lastly it will try to use Azure CLI to get the token. I would say that you are logged in the Azure CLI on the machine and it is able to get the token using it - that's why one of the run works. The other one fails, because it races with the first one to get the token using CLI but fails.

This might be completely wrong though - I did assume a couple of things here.

To confirm:
1. What auth method you tried to use here?
2. Is AzureCLI available in the runner & is it authenticated?

**Comment by SSKLCP** [comment]
Hey, 

So I switched to using AZURE_* as the environment variables (I was on KVENV_*) and now it seems to work fine? 

I'm a little confused as I don't think I have CLI installed (though it could be an Atlantis dependency) and the only credentials I've provided (not through kvenv) are the KVENV_ environment variables! So I don't know how it works for single runs all this time. 

But thanks for taking a look at this so quickly :) It seems to be working for me now! 
Definitely a handy tool
